# 异常体系

## Java异常体系介绍

![](assets/image-20220712221934245.png)

Throwable：整个Java异常体系的顶层父类，它有两个子类：

-   Error：系统致命错误，程序无法处理的错误，由JVM产生和抛出的，比如OutOfMemoryError、StackOverflowError、ThreadDeath等。这些错误发生时，Java虚拟机只能终止线程。
-   Exception：程序本身可以处理的异常，这种异常分两大类运行时异常和非运行时异常。

![](assets/image-20220712222002081.png)

-   RuntimeException（也称不受检异常Unchecked Exception）：即可以编译通过，一般由程序的逻辑错误引起，开发过程中应尽量避免，自定义异常一般继承此类。
-   RuntimeException以外的异常（也称受检异常Check Exception）：编译器在编译阶段进行处理，程序必须处理此类异常否则无法通过编译。

## 基本语法

```
try{  
  //（尝试运行的）程序代码  
}catch(异常类型 异常的变量名){  
  //异常处理代码  
}finally{  
  //异常发生，方法返回之前，总是要执行的代码  
} 
```

注意

-   try、catch、finally三个语句块均不能单独使用，三者可以组成 try...catch...finally、try...catch、try...finally三种结构，catch语句可以有一个或多个，finally语句最多一个
-   try、catch、finally三个代码块中变量的作用域为代码块内部，分别独立而不能相互访问
-   多个catch块时候，只会匹配其中一个异常类并执行catch块代码，而不会再执行别的catch块，并且匹配catch语句的顺序是由上到下
-   先Catch子类异常再Catch父类异常

Q:以下程序会输出什么？

```
public static void main(String[] args) {
    try {
        String a = null;
        System.out.println(a.length());
        System.out.println("try end.");
    } catch (NullPointerException e) {
        System.out.println("catch null.");
    } catch (Exception e) {
        System.out.println("catch all type.");
    } finally {
        System.out.println("finally.");
    }
    ystem.out.println("code end.");
}
```

控制台输出：

```
catch null.
finally.
code end.
```

拓展：去除所有catch打印结果

```
finally.
Exception in thread "main" java.lang.NullPointerException
at com.huawei.cloudsop.csmonitorservice.util.PropertiesFile.testException(PropertiesFile.java:68)
at com.huawei.cloudsop.csmonitorservice.util.PropertiesFile.main(PropertiesFile.java:92)
```

